import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-student-list',
  templateUrl: './student-list.component.html',
  styleUrls: ['./student-list.component.css'],
  standalone: true,
  imports: [CommonModule, RouterModule],
})
export class StudentListComponent {
  students = [
    {
      id: 1,
      firstName: 'John',
      lastName: 'Doe',
      studentId: '2025-0001',
      email: 'john.doe@example.com',
      degree: 'B.Sc. Computer Science',
      year: 3,
      gpa: 3.8,
      courses: 8,
      grades: 7,
      attendance: '95%',
      advisor: 'Dr. Smith',
      status: 'Active',
    },
    {
      id: 2,
      firstName: 'Jane',
      lastName: 'Smith',
      studentId: '2024-0002',
      email: 'jane.smith@example.com',
      degree: 'B.A. English',
      year: 2,
      gpa: 3.6,
      courses: 7,
      grades: 6,
      attendance: '92%',
      advisor: 'Dr. Johnson',
      status: 'Active',
    },
    {
      id: 3,
      firstName: 'Alice',
      lastName: 'Johnson',
      studentId: '2023-0003',
      email: 'alice.johnson@example.com',
      degree: 'B.Sc. Mathematics',
      year: 4,
      gpa: 3.9,
      courses: 9,
      grades: 9,
      attendance: '98%',
      advisor: 'Dr. Allen',
      status: 'Graduating',
    },
    {
      id: 4,
      firstName: 'Michael',
      lastName: 'Brown',
      studentId: '2025-0004',
      email: 'michael.brown@example.com',
      degree: 'B.Sc. Physics',
      year: 3,
      gpa: 3.5,
      courses: 8,
      grades: 7,
      attendance: '91%',
      advisor: 'Dr. Carter',
      status: 'Active',
    },
    {
      id: 5,
      firstName: 'Emily',
      lastName: 'Davis',
      studentId: '2023-0005',
      email: 'emily.davis@example.com',
      degree: 'B.A. History',
      year: 4,
      gpa: 3.7,
      courses: 9,
      grades: 8,
      attendance: '89%',
      advisor: 'Dr. Adams',
      status: 'Graduating',
    },
    {
      id: 6,
      firstName: 'Daniel',
      lastName: 'Miller',
      studentId: '2022-0006',
      email: 'daniel.miller@example.com',
      degree: 'B.Sc. Chemistry',
      year: 4,
      gpa: 3.4,
      courses: 9,
      grades: 8,
      attendance: '87%',
      advisor: 'Dr. Garcia',
      status: 'Graduated',
    },
    {
      id: 7,
      firstName: 'Sophia',
      lastName: 'Martinez',
      studentId: '2024-0007',
      email: 'sophia.martinez@example.com',
      degree: 'B.Sc. Biology',
      year: 2,
      gpa: 3.9,
      courses: 7,
      grades: 6,
      attendance: '93%',
      advisor: 'Dr. Lee',
      status: 'Active',
    },
    {
      id: 8,
      firstName: 'Oliver',
      lastName: 'Taylor',
      studentId: '2025-0008',
      email: 'oliver.taylor@example.com',
      degree: 'B.Sc. Data Science',
      year: 3,
      gpa: 3.8,
      courses: 8,
      grades: 7,
      attendance: '94%',
      advisor: 'Dr. Walker',
      status: 'Active',
    },
    {
      id: 9,
      firstName: 'Isabella',
      lastName: 'Hernandez',
      studentId: '2023-0009',
      email: 'isabella.hernandez@example.com',
      degree: 'B.A. Psychology',
      year: 4,
      gpa: 3.6,
      courses: 9,
      grades: 8,
      attendance: '90%',
      advisor: 'Dr. Robinson',
      status: 'Graduating',
    },
    {
      id: 10,
      firstName: 'William',
      lastName: 'Lopez',
      studentId: '2024-0010',
      email: 'william.lopez@example.com',
      degree: 'B.Sc. Geology',
      year: 2,
      gpa: 3.3,
      courses: 7,
      grades: 6,
      attendance: '88%',
      advisor: 'Dr. Moore',
      status: 'Active',
    },
    {
      id: 11,
      firstName: 'Mia',
      lastName: 'Wilson',
      studentId: '2022-0011',
      email: 'mia.wilson@example.com',
      degree: 'B.Sc. Environmental Science',
      year: 4,
      gpa: 3.8,
      courses: 9,
      grades: 8,
      attendance: '96%',
      advisor: 'Dr. White',
      status: 'Graduated',
    },
  ];

  deleteStudent(id: number): void {
    if (confirm('Are you sure you want to delete this student?')) {
      this.students = this.students.filter((student) => student.id !== id);
    }
  }
}
